spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sai?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  redis:
    host: 127.0.0.1 # Redis 服务 IP 地址
    port: 6379 # Redis 服务端口号
    database: 0 # Redis 服务数据库索引
    password: # Redis 服务连接密码
    timeout: 3000 # Redis 服务连接超时时间（毫秒）

logging:
  level:
    com.wen.sai: debug